name: Build MEDLINK APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Installer Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Installer Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Installer dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            autopoint \
            libtool \
            pkg-config \
            cmake \
            libffi-dev \
            libssl-dev \
            gettext \
            build-essential

      - name: Installer Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.34

      - name: Installer Android SDK
        uses: android-actions/setup-android@v4

      - name: Accepter licences Android
        run: |
          yes | sdkmanager --licenses || true

      - name: Installer composants Android
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"

      - name: Nettoyer ancien build
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Construire MEDLINK
        run: |
          buildozer -v android debug

      - name: Vérifier APK
        run: |
          ls -lh bin/

      - name: Publier APK
        uses: actions/upload-artifact@v4
        with:
          name: MEDLINK-APK
          path: bin/*.apk
